version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    tty: true
    ports:
      - '8000:8000'

    depends_on:
      - db